import { MenuCategory, MenuItem, Testimonial, GalleryImage } from './types';

export const NAV_LINKS = [
  { name: 'Home', href: '#home' },
  { name: 'Menu', href: '#menu' },
  { name: 'Gallery', href: '#gallery' },
  { name: 'Contact', href: '#contact' },
];

export const MENU_ITEMS: MenuItem[] = [
  // SOUTH INDIAN
  { id: '1', category: MenuCategory.SOUTH_INDIAN, name: 'Steam Idli', price: '₹70.0' },
  { id: '2', category: MenuCategory.SOUTH_INDIAN, name: 'Idli Fry', price: '₹110.0' },
  { id: '3', category: MenuCategory.SOUTH_INDIAN, name: 'Dahi Wada', price: '₹110.0' },
  { id: '4', category: MenuCategory.SOUTH_INDIAN, name: 'Dahi Idli', price: '₹110.0' },
  { id: '5', category: MenuCategory.SOUTH_INDIAN, name: 'Medu Wada', price: '₹90.0' },
  { id: '6', category: MenuCategory.SOUTH_INDIAN, name: 'Idli Wada', price: '₹80.0' },
  { id: '7', category: MenuCategory.SOUTH_INDIAN, name: 'Upma', price: '₹70.0' },
  { id: '8', category: MenuCategory.SOUTH_INDIAN, name: 'Sheera', price: '₹80.0' },
  { id: '9', category: MenuCategory.SOUTH_INDIAN, name: 'Upma Sheera Mix', price: '₹80.0' },
  { id: '10', category: MenuCategory.SOUTH_INDIAN, name: 'Puri Bhaji', price: '₹110.0' },
  
  // DOSA
  { id: '11', category: MenuCategory.DOSA, name: 'Sada Dosa', price: '₹80.0' },
  { id: '12', category: MenuCategory.DOSA, name: 'Masala Dosa', price: '₹90.0' },
  { id: '13', category: MenuCategory.DOSA, name: 'Rawa Sada Dosa', price: '₹110.0' },
  { id: '14', category: MenuCategory.DOSA, name: 'Rawa Masala Dosa', price: '₹120.0' },
  { id: '15', category: MenuCategory.DOSA, name: 'Onion Rawa Sada Dosa', price: '₹120.0' },
  { id: '16', category: MenuCategory.DOSA, name: 'Onion Rawa Masala', price: '₹130.0' },
  { id: '17', category: MenuCategory.DOSA, name: 'Mysore Sada Dosa', price: '₹105.0' },
  { id: '18', category: MenuCategory.DOSA, name: 'Mysore Masala Dosa', price: '₹115.0' },
  { id: '19', category: MenuCategory.DOSA, name: 'Tomato Omlette', price: '₹100.0' },
  { id: '20', category: MenuCategory.DOSA, name: 'Ghee Dosa', price: '₹100.0' },
  { id: '21', category: MenuCategory.DOSA, name: 'Ghee Masala Dosa', price: '₹120.0' },

  // SPL DOSA
  { id: '22', category: MenuCategory.SPL_DOSA, name: 'Paneer Sada Dosa', price: '₹150.0' },
  { id: '23', category: MenuCategory.SPL_DOSA, name: 'Paneer Masala Dosa', price: '₹170.0' },
  { id: '24', category: MenuCategory.SPL_DOSA, name: 'Ragi Sada Dosa', price: '₹140.0' },
  { id: '25', category: MenuCategory.SPL_DOSA, name: 'Ragi Masala Dosa', price: '₹180.0' },
  { id: '26', category: MenuCategory.SPL_DOSA, name: 'Peri Peri Dosa', price: '₹150.0' },
  { id: '27', category: MenuCategory.SPL_DOSA, name: 'Set Dosa', price: '₹150.0' },
  { id: '28', category: MenuCategory.SPL_DOSA, name: 'Davangere Benne Dosa', price: '₹210.0' },
  { id: '29', category: MenuCategory.SPL_DOSA, name: 'Add Butter/Cheese', price: '₹40.0' },

  // UTTAPPA
  { id: '30', category: MenuCategory.UTTAPPA, name: 'Sada Uttappa', price: '₹80.0' },
  { id: '31', category: MenuCategory.UTTAPPA, name: 'Tomato Uttappa', price: '₹100.0' },
  { id: '32', category: MenuCategory.UTTAPPA, name: 'Onion Uttappa', price: '₹110.0' },
  { id: '33', category: MenuCategory.UTTAPPA, name: 'Masala Uttappa', price: '₹110.0' },
  { id: '34', category: MenuCategory.UTTAPPA, name: 'Tomato Onion Uttappa', price: '₹110.0' },
  { id: '35', category: MenuCategory.UTTAPPA, name: 'Coconut Uttappa', price: '₹110.0' },
  { id: '36', category: MenuCategory.UTTAPPA, name: 'Cheff Spl Uttappam', price: '₹130.0' },
  { id: '37', category: MenuCategory.UTTAPPA, name: 'Add Butter/Cheese /Ghee', price: '₹40.0' },

  // MUMBAI SPECIAL
  { id: '38', category: MenuCategory.MUMBAI_SPECIAL, name: 'Batata Vada', price: '₹70.0' },
  { id: '39', category: MenuCategory.MUMBAI_SPECIAL, name: 'Batata Vada Usal', price: '₹100.0' },
  { id: '40', category: MenuCategory.MUMBAI_SPECIAL, name: 'Misal Pav', price: '₹85.0' },
  { id: '41', category: MenuCategory.MUMBAI_SPECIAL, name: 'Kanda Poha', price: '₹70.0' },
  { id: '42', category: MenuCategory.MUMBAI_SPECIAL, name: 'Plain Pav', price: '₹6.0' },

  // HOT BEVERAGE
  { id: '43', category: MenuCategory.HOT_BEVERAGE, name: 'Tea', price: '₹25.0' },
  { id: '44', category: MenuCategory.HOT_BEVERAGE, name: 'Black Tea', price: '₹20.0' },
  { id: '45', category: MenuCategory.HOT_BEVERAGE, name: 'Green Tea', price: '₹45.0' },
  { id: '46', category: MenuCategory.HOT_BEVERAGE, name: 'Nescafe', price: '₹50.0' },
  { id: '47', category: MenuCategory.HOT_BEVERAGE, name: 'Black Coffee', price: '₹45.0' },
  { id: '48', category: MenuCategory.HOT_BEVERAGE, name: 'Filter Coffee', price: '₹40.0' },
  { id: '49', category: MenuCategory.HOT_BEVERAGE, name: 'Hot Chocolate (Cup)', price: '₹90.0' },
  { id: '50', category: MenuCategory.HOT_BEVERAGE, name: 'Milk Bournvita', price: '₹80.0' },
  { id: '51', category: MenuCategory.HOT_BEVERAGE, name: 'Masala Milk', price: '₹70.0' },

  // PAV BHAJI
  { id: '52', category: MenuCategory.PAV_BHAJI, name: 'Pav Bhaji', price: '₹140.0' },
  { id: '53', category: MenuCategory.PAV_BHAJI, name: 'Only Bhaji', price: '₹120.0' },
  { id: '54', category: MenuCategory.PAV_BHAJI, name: 'Khada Pav Bhaji', price: '₹155.0' },
  { id: '55', category: MenuCategory.PAV_BHAJI, name: 'Only Khada Bhaji', price: '₹130.0' },
  { id: '56', category: MenuCategory.PAV_BHAJI, name: 'Jain Pav Bhaji', price: '₹160.0' },
  { id: '57', category: MenuCategory.PAV_BHAJI, name: 'Special Pav Bhaji', price: '₹190.0' },
  { id: '58', category: MenuCategory.PAV_BHAJI, name: 'Cheese Pav Bhaji', price: '₹180.0' },
  { id: '59', category: MenuCategory.PAV_BHAJI, name: 'Masala Pav', price: '₹100.0' },
  { id: '60', category: MenuCategory.PAV_BHAJI, name: 'Cheese Masala Pav', price: '₹150.0' },
  { id: '61', category: MenuCategory.PAV_BHAJI, name: 'Extra Pav (Single)', price: '₹15.0' },
  { id: '62', category: MenuCategory.PAV_BHAJI, name: 'Extra Cheese', price: '₹40.0' },
  { id: '63', category: MenuCategory.PAV_BHAJI, name: 'Extra Butter', price: '₹30.0' },

  // CHINESE SOUP
  { id: '64', category: MenuCategory.CHINESE_SOUP, name: 'Cream Of Mushroom', price: '₹150.0' },
  { id: '65', category: MenuCategory.CHINESE_SOUP, name: 'Cream Of Spinach', price: '₹130.0' },
  { id: '66', category: MenuCategory.CHINESE_SOUP, name: 'Cream Of Tomato', price: '₹130.0' },
  { id: '67', category: MenuCategory.CHINESE_SOUP, name: 'Cream Of Broccoli', price: '₹160.0' },
  { id: '68', category: MenuCategory.CHINESE_SOUP, name: 'Dal Ka Shorba', price: '₹150.0' },
  { id: '69', category: MenuCategory.CHINESE_SOUP, name: 'Spinach Shorba', price: '₹170.0' },
  { id: '70', category: MenuCategory.CHINESE_SOUP, name: 'Veg Clear Soup', price: '₹115.0' },
  { id: '71', category: MenuCategory.CHINESE_SOUP, name: 'Sweet Corn Plain Soup', price: '₹130.0' },
  { id: '72', category: MenuCategory.CHINESE_SOUP, name: 'Manchow Soup', price: '₹130.0' },
  { id: '73', category: MenuCategory.CHINESE_SOUP, name: 'Hot & Sour Soup', price: '₹130.0' },
  { id: '74', category: MenuCategory.CHINESE_SOUP, name: 'Lemon Coriander Soup', price: '₹150.0' },
  { id: '75', category: MenuCategory.CHINESE_SOUP, name: 'Veg Noodles Soup', price: '₹140.0' },

  // KOFTA
  { id: '76', category: MenuCategory.KOFTA, name: 'Veg Kofta', price: '₹230.0' },
  { id: '77', category: MenuCategory.KOFTA, name: 'Malai Kofta', price: '₹280.0' },
  { id: '78', category: MenuCategory.KOFTA, name: 'Paneer Kofta', price: '₹270.0' },

  // INDIAN MAIN COURSE
  { id: '79', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Chana Masala', price: '₹180.0' },
  { id: '80', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Aloo Palak', price: '₹180.0' },
  { id: '81', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Aloo Mutter', price: '₹180.0' },
  { id: '82', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Sev Tomato', price: '₹190.0' },
  { id: '83', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Tomato Bharta', price: '₹180.0' },
  { id: '84', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Baigan Bharta', price: '₹210.0' },
  { id: '85', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Baigan Masala', price: '₹210.0' },
  { id: '86', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Bhendi Masala', price: '₹210.0' },
  { id: '87', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Bhendi Fry', price: '₹210.0' },
  { id: '88', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Bhindi Do Pyaaza', price: '₹220.0' },
  { id: '89', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Veg Handi', price: '₹220.0' },
  { id: '90', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Veg Kadai', price: '₹225.0' },
  { id: '91', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Mix Veg', price: '₹225.0' },
  { id: '92', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Veg Kolhapuri', price: '₹230.0' },
  { id: '93', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Veg Kheema', price: '₹230.0' },
  { id: '94', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Veg Makkanwala', price: '₹220.0' },
  { id: '95', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Veg Lajawab', price: '₹220.0' },
  { id: '96', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Veg Lasooni', price: '₹240.0' },
  { id: '97', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Diwani Handi', price: '₹230.0' },
  { id: '98', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Kaju Masala', price: '₹290.0' },
  { id: '99', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Dum Aloo Punjabi', price: '₹240.0' },
  { id: '100', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Navratan Kurma', price: '₹270.0' },
  { id: '101', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Paneer Tikka Masala', price: '₹275.0' },
  { id: '102', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Palak Paneer', price: '₹260.0' },
  { id: '103', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Paneer Butter Masala', price: '₹260.0' },
  { id: '104', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Mutter Paneer', price: '₹250.0' },
  { id: '105', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Paneer Peshawari', price: '₹270.0' },
  { id: '106', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Paneer Masala', price: '₹260.0' },
  { id: '107', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Paneer Handi', price: '₹260.0' },
  { id: '108', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Paneer Kolhapuri', price: '₹260.0' },
  { id: '109', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Paneer Laziz', price: '₹275.0' },
  { id: '110', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Kaju Paneer', price: '₹290.0' },
  { id: '111', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Paneer Kadai', price: '₹260.0' },
  { id: '112', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Paneer Bhurji', price: '₹315.0' },
  { id: '113', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Mushroom Masala', price: '₹260.0' },
  { id: '114', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Methi Mutter Masala', price: '₹240.0' },
  { id: '115', category: MenuCategory.INDIAN_MAIN_COURSE, name: 'Baby Corn Mushroom Masala', price: '₹260.0' },

  // TANDOORI STARTERS
  { id: '116', category: MenuCategory.TANDOORI_STARTERS, name: 'Aloo Gobi Tikka', price: '₹190.0' },
  { id: '117', category: MenuCategory.TANDOORI_STARTERS, name: 'Paneer Tikka', price: '₹250.0' },
  { id: '118', category: MenuCategory.TANDOORI_STARTERS, name: 'Paneer Lasooni Tikka', price: '₹260.0' },
  { id: '119', category: MenuCategory.TANDOORI_STARTERS, name: 'Paneer Banjara Tikka', price: '₹270.0' },
  { id: '120', category: MenuCategory.TANDOORI_STARTERS, name: 'Paneer Malai Tikka', price: '₹260.0' },
  { id: '121', category: MenuCategory.TANDOORI_STARTERS, name: 'Paneer Kalimiri Tikka', price: '₹270.0' },
  { id: '122', category: MenuCategory.TANDOORI_STARTERS, name: 'Mushroom Tikka', price: '₹220.0' },

  // CHINESE RICE / NOODLES
  { id: '123', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Veg Fried Rice', price: '₹210.0' },
  { id: '124', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Pot Rice', price: '₹315.0' },
  { id: '125', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Burnt Garlic Rice', price: '₹240.0' },
  { id: '126', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Schezwan Fried Rice', price: '₹220.0' },
  { id: '127', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Mushroom Fried Rice', price: '₹230.0' },
  { id: '128', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Chilly Garlic Rice', price: '₹230.0' },
  { id: '129', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Triple Schezwan Fried Rice', price: '₹290.0' },
  { id: '130', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Paneer Fried Rice', price: '₹270.0' },
  { id: '131', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Manchurian Fried Rice', price: '₹260.0' },
  { id: '132', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Veg Hakka Noodles', price: '₹210.0' },
  { id: '133', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Schezwan Noodles', price: '₹220.0' },
  { id: '134', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Hong Kong Noodles', price: '₹230.0' },
  { id: '135', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Singapuri Noodles', price: '₹230.0' },
  { id: '136', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Chilly Garlic Noodles', price: '₹230.0' },
  { id: '137', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Golden Mushroom Noodles', price: '₹240.0' },
  { id: '138', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Peri Peri Noodles', price: '₹260.0' },
  { id: '139', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Triple Schezwan Noodles', price: '₹290.0' },
  { id: '140', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Manchurian Noodles', price: '₹260.0' },
  { id: '141', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Shri Gopal Krishnas Spl Veg Thali', price: '₹220.0' },
  { id: '142', category: MenuCategory.CHINESE_RICE_NOODLES, name: 'Veg Thali', price: '₹190.0' },

  // KHANE KE SATHI
  { id: '143', category: MenuCategory.KHANE_KE_SATHI, name: 'Roti', price: '₹26.0' },
  { id: '144', category: MenuCategory.KHANE_KE_SATHI, name: 'Butter Roti', price: '₹32.0' },
  { id: '145', category: MenuCategory.KHANE_KE_SATHI, name: 'Kulcha', price: '₹45.0' },
  { id: '146', category: MenuCategory.KHANE_KE_SATHI, name: 'Butter Kulcha', price: '₹50.0' },
  { id: '147', category: MenuCategory.KHANE_KE_SATHI, name: 'Lacchha Paratha', price: '₹50.0' },
  { id: '148', category: MenuCategory.KHANE_KE_SATHI, name: 'Butter Garlic Naan', price: '₹90.0' },
  { id: '149', category: MenuCategory.KHANE_KE_SATHI, name: 'Butter Lacchha Paratha', price: '₹60.0' },
  { id: '150', category: MenuCategory.KHANE_KE_SATHI, name: 'Methi Paratha', price: '₹75.0' },
  { id: '151', category: MenuCategory.KHANE_KE_SATHI, name: 'Naan', price: '₹50.0' },
  { id: '152', category: MenuCategory.KHANE_KE_SATHI, name: 'Butter Naan', price: '₹65.0' },
  { id: '153', category: MenuCategory.KHANE_KE_SATHI, name: 'Garlic Naan', price: '₹75.0' },
  { id: '154', category: MenuCategory.KHANE_KE_SATHI, name: 'Cheese Naan', price: '₹90.0' },
  { id: '155', category: MenuCategory.KHANE_KE_SATHI, name: 'Cheese Garlic Naan', price: '₹110.0' },
  { id: '156', category: MenuCategory.KHANE_KE_SATHI, name: 'Aloo Paratha', price: '₹110.0' },
  { id: '157', category: MenuCategory.KHANE_KE_SATHI, name: 'Gobi Paratha', price: '₹120.0' },
  { id: '158', category: MenuCategory.KHANE_KE_SATHI, name: 'Paneer Paratha', price: '₹140.0' },
  { id: '159', category: MenuCategory.KHANE_KE_SATHI, name: 'Chapati', price: '₹15.0' },
  { id: '160', category: MenuCategory.KHANE_KE_SATHI, name: 'Butter Chapati', price: '₹20.0' },

  // RICE AND BIRYANI
  { id: '161', category: MenuCategory.RICE_BIRYANI, name: 'Steam Rice', price: '₹110.0' },
  { id: '162', category: MenuCategory.RICE_BIRYANI, name: 'Jeera Rice', price: '₹110.0' },
  { id: '163', category: MenuCategory.RICE_BIRYANI, name: 'Dal Khichadi', price: '₹180.0' },
  { id: '164', category: MenuCategory.RICE_BIRYANI, name: 'Palak Khichadi', price: '₹190.0' },
  { id: '165', category: MenuCategory.RICE_BIRYANI, name: 'Dal Khichadi Tadka', price: '₹190.0' },
  { id: '166', category: MenuCategory.RICE_BIRYANI, name: 'Masala Veg Khichadi', price: '₹230.0' },
  { id: '167', category: MenuCategory.RICE_BIRYANI, name: 'Veg Pulao', price: '₹190.0' },
  { id: '168', category: MenuCategory.RICE_BIRYANI, name: 'Kashmiri Pulao', price: '₹200.0' },
  { id: '169', category: MenuCategory.RICE_BIRYANI, name: 'Lemon Rice', price: '₹190.0' },
  { id: '170', category: MenuCategory.RICE_BIRYANI, name: 'Veg Biryani', price: '₹210.0' },
  { id: '171', category: MenuCategory.RICE_BIRYANI, name: 'Veg Dum Biryani', price: '₹230.0' },
  { id: '172', category: MenuCategory.RICE_BIRYANI, name: 'Veg Hyderabad Biryani', price: '₹240.0' },
  { id: '173', category: MenuCategory.RICE_BIRYANI, name: 'Paneer Biryani', price: '₹260.0' },
  { id: '174', category: MenuCategory.RICE_BIRYANI, name: 'Mushroom Biryani', price: '₹240.0' },
  { id: '175', category: MenuCategory.RICE_BIRYANI, name: 'Curd Rice', price: '₹190.0' },

  // FRESH JUICES
  { id: '176', category: MenuCategory.FRESH_JUICES, name: 'Mango Juice', price: '₹130.0' },
  { id: '177', category: MenuCategory.FRESH_JUICES, name: 'Apple Juice', price: '₹110.0' },
  { id: '178', category: MenuCategory.FRESH_JUICES, name: 'Pineapple Juice', price: '₹110.0' },
  { id: '179', category: MenuCategory.FRESH_JUICES, name: 'Water Melon Juice', price: '₹95.0' },
  { id: '180', category: MenuCategory.FRESH_JUICES, name: 'Sweet Lime mousambi', price: '₹110.0' },
  { id: '181', category: MenuCategory.FRESH_JUICES, name: 'Orange Juice', price: '₹110.0' },
  { id: '182', category: MenuCategory.FRESH_JUICES, name: 'Cocktail Juice', price: '₹120.0' },
  { id: '183', category: MenuCategory.FRESH_JUICES, name: 'Grapes Juice', price: '₹130.0' },
  { id: '184', category: MenuCategory.FRESH_JUICES, name: 'Pomegranate anar', price: '₹140.0' },
  { id: '185', category: MenuCategory.FRESH_JUICES, name: 'Fresh Lime Soda sweet & Salt', price: '₹70.0' },
  { id: '186', category: MenuCategory.FRESH_JUICES, name: 'Fresh Lime Water sweet & Salt', price: '₹50.0' },

  // MILK SHAKE
  { id: '187', category: MenuCategory.MILK_SHAKE, name: 'Cold Coffee', price: '₹150.0' },
  { id: '188', category: MenuCategory.MILK_SHAKE, name: 'Banana Milkshake', price: '₹130.0' },
  { id: '189', category: MenuCategory.MILK_SHAKE, name: 'Chickoo Milkshake', price: '₹130.0' },
  { id: '190', category: MenuCategory.MILK_SHAKE, name: 'Pineapple Milkshake', price: '₹130.0' },
  { id: '191', category: MenuCategory.MILK_SHAKE, name: 'Chocolate Milkshake', price: '₹160.0' },
  { id: '192', category: MenuCategory.MILK_SHAKE, name: 'Mango Milkshake', price: '₹160.0' },
  { id: '193', category: MenuCategory.MILK_SHAKE, name: 'Strawberry/Sitaphal Milkshake', price: '₹160.0' },
  { id: '194', category: MenuCategory.MILK_SHAKE, name: 'Butter Scotch Milkshake', price: '₹150.0' },
  { id: '195', category: MenuCategory.MILK_SHAKE, name: 'Kesar Milkshake', price: '₹150.0' },
  { id: '196', category: MenuCategory.MILK_SHAKE, name: 'Anjeer Milkshake', price: '₹180.0' },
  { id: '197', category: MenuCategory.MILK_SHAKE, name: 'Kaju Badam/Badam Pista', price: '₹210.0' },
  { id: '198', category: MenuCategory.MILK_SHAKE, name: 'Pista Milkshake', price: '₹230.0' },
  { id: '199', category: MenuCategory.MILK_SHAKE, name: 'Mix Dry Fruit Milkshake', price: '₹230.0' },
  { id: '200', category: MenuCategory.MILK_SHAKE, name: 'Oreo Milkshake', price: '₹160.0' },

  // TAWA RICE
  { id: '201', category: MenuCategory.TAWA_RICE, name: 'Tawa Pulao', price: '₹190.0' },
  { id: '202', category: MenuCategory.TAWA_RICE, name: 'Mushroom Tawa Pulao', price: '₹220.0' },
  { id: '203', category: MenuCategory.TAWA_RICE, name: 'Cheese Tawa Pulao', price: '₹260.0' },
  { id: '204', category: MenuCategory.TAWA_RICE, name: 'Spl. Tawa Pulao', price: '₹260.0' },
  { id: '205', category: MenuCategory.TAWA_RICE, name: 'Corn Tawa Pulao', price: '₹220.0' },
  { id: '206', category: MenuCategory.TAWA_RICE, name: 'Paneer Tawa Pulao', price: '₹250.0' },
  { id: '207', category: MenuCategory.TAWA_RICE, name: 'Shri Gopal Krishnas Tawa Pulao', price: '₹270.0' },

  // DAL
  { id: '208', category: MenuCategory.DAL, name: 'Dal Fry', price: '₹130.0' },
  { id: '209', category: MenuCategory.DAL, name: 'Dal Tadka', price: '₹140.0' },
  { id: '210', category: MenuCategory.DAL, name: 'Dal Makhani', price: '₹190.0' },
  { id: '211', category: MenuCategory.DAL, name: 'Palak Dal', price: '₹170.0' },
  { id: '212', category: MenuCategory.DAL, name: 'Dal Kolhapuri', price: '₹160.0' },

  // COLD & BEVERAGES
  { id: '213', category: MenuCategory.COLD_BEVERAGES, name: 'Packaged Water', price: '₹30.0' },
  { id: '214', category: MenuCategory.COLD_BEVERAGES, name: 'Soft Drink 300 MI', price: '₹30.0' },
  { id: '215', category: MenuCategory.COLD_BEVERAGES, name: 'Soft Drink 750 MI', price: '₹50.0' },
  { id: '216', category: MenuCategory.COLD_BEVERAGES, name: 'Butter Milk Plain', price: '₹45.0' },
  { id: '217', category: MenuCategory.COLD_BEVERAGES, name: 'Butter Milk Masala', price: '₹50.0' },
  { id: '218', category: MenuCategory.COLD_BEVERAGES, name: 'Sweet Lassi', price: '₹80.0' },
  { id: '219', category: MenuCategory.COLD_BEVERAGES, name: 'Mango Lassi', price: '₹95.0' },

  // RAITA
  { id: '220', category: MenuCategory.RAITA, name: 'Plain Curd', price: '₹60.0' },
  { id: '221', category: MenuCategory.RAITA, name: 'Boondi Raita', price: '₹80.0' },
  { id: '222', category: MenuCategory.RAITA, name: 'Veg Raita', price: '₹70.0' },
  { id: '223', category: MenuCategory.RAITA, name: 'Pineapple Raita', price: '₹90.0' },

  // PAPAD
  { id: '224', category: MenuCategory.PAPAD, name: 'Roasted Papad', price: '₹30.0' },
  { id: '225', category: MenuCategory.PAPAD, name: 'Fry Papad', price: '₹35.0' },
  { id: '226', category: MenuCategory.PAPAD, name: 'Masala Papad', price: '₹50.0' },
  { id: '227', category: MenuCategory.PAPAD, name: 'Cheese Masala Papad', price: '₹100.0' },

  // SALAD
  { id: '228', category: MenuCategory.SALAD, name: 'Tossed Salad', price: '₹120.0' },
  { id: '229', category: MenuCategory.SALAD, name: 'Garden Fresh Salad', price: '₹90.0' },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Rahul Mehta',
    role: 'Local Resident',
    content: "The Pav Bhaji here is legendary in Bhandup. Pure authentic Mumbai taste. Quick service and very clean.",
    rating: 5,
  },
  {
    id: 't2',
    name: 'Priya Shetty',
    role: 'Foodie',
    content: "Great place for South Indian breakfast. The Sambhar is perfect. Also love their Jain options.",
    rating: 5,
  },
  {
    id: 't3',
    name: 'Amit Singh',
    role: 'Regular Customer',
    content: "We always order home delivery from SGK. Food always arrives hot and the quantity is generous.",
    rating: 4,
  },
];

export const GALLERY_IMAGES: GalleryImage[] = [
    {
        id: 'g1',
        url: '/SGK1.jpeg', 
        alt: 'Radhe Krishna Mural',
    },
    {
        id: 'g2',
        url: '/SGK2.jpeg',
        alt: 'Divine Krishna Art',
    },
    {
        id: 'g3',
        url: '/SGK3.jpeg',
        alt: 'Restaurant Interior - Main Hall',
    },
    {
        id: 'g4',
        url: '/SGK4.jpeg',
        alt: 'Restaurant Interior - Seating',
    },
    {
        id: 'g5',
        url: '/SGK5.jpeg',
        alt: 'Wall Art and Ambience',
    },
    {
        id: 'g6',
        url: '/SGK6.jpeg',
        alt: 'Dining Area',
    },
    {
        id: 'g7',
        url: '/SGK7.jpeg',
        alt: 'Spacious Dining Hall',
    },
    {
        id: 'g8',
        url: '/SGK8.jpeg',
        alt: 'Restaurant Seating Arrangement',
    }
];